[project]
name = "niwrap"
version = "0.6.1"
description = "Neuroimaging Python wrappers"
readme = "README.md"
license = "LGPL-2.1"
authors = [{ name = "CMI DAIR", email = "dair@childmind.org" }]
requires-python = ">=3.10"
dependencies = [
  "styxdocker",
  "styxsingularity",
  "styxgraph",
  "niwrap_fastsurfer==0.6.1",
  "niwrap_ants==0.6.1",
  "niwrap_freesurfer==0.6.1",
  "niwrap_fsl==0.6.1",
  "niwrap_niftyreg==0.6.1",
  "niwrap_mrtrix==0.6.1",
  "niwrap_dcm2niix==0.6.1",
  "niwrap_afni==0.6.1",
  "niwrap_c3d==0.6.1",
  "niwrap_workbench==0.6.1",
  "niwrap_greedy==0.6.1",
  "niwrap_mrtrix3tissue==0.6.1"
]

[tool.hatch.build.targets.wheel]
packages = ["src/niwrap"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"